from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

from .models import AnalysisIssue, AnalysisReport, AnalysisSession


MockOutcome = Literal["ok", "warning", "fatal", "exception"]


@dataclass(frozen=True)
class MockAnalysisTask:
    analysis_id: str
    title: str
    outcome: MockOutcome = "ok"

    def run(self, session: AnalysisSession) -> AnalysisReport:
        if self.outcome == "exception":
            raise RuntimeError(f"Mock exception from {self.analysis_id}")

        if self.outcome == "warning":
            warning = AnalysisIssue(
                severity="warning",
                code="MOCK_WARNING",
                message="Mock warning generated by analysis pipeline test.",
                analysis_id=self.analysis_id,
            )
            return AnalysisReport(
                report_id=f"{session.session_id}:{self.analysis_id}",
                analysis_id=self.analysis_id,
                title=self.title,
                status="warning",
                summary="Mock analysis completed with warning.",
                issues=(warning,),
                metadata={"mock": True},
            )

        if self.outcome == "fatal":
            fatal = AnalysisIssue(
                severity="fatal",
                code="MOCK_FATAL",
                message="Mock fatal error generated by analysis pipeline test.",
                analysis_id=self.analysis_id,
            )
            return AnalysisReport(
                report_id=f"{session.session_id}:{self.analysis_id}",
                analysis_id=self.analysis_id,
                title=self.title,
                status="failed",
                summary="Mock analysis failed.",
                issues=(fatal,),
                metadata={"mock": True},
            )

        return AnalysisReport(
            report_id=f"{session.session_id}:{self.analysis_id}",
            analysis_id=self.analysis_id,
            title=self.title,
            status="ok",
            summary="Mock analysis completed successfully.",
            issues=(),
            metadata={"mock": True},
        )


def build_default_mock_analysis_queue() -> list[MockAnalysisTask]:
    return [
        MockAnalysisTask(
            analysis_id="mock_pull_direction_placeholder",
            title="Mock Pull Direction Placeholder",
        ),
        MockAnalysisTask(
            analysis_id="mock_draft_placeholder",
            title="Mock Draft Placeholder",
        ),
        MockAnalysisTask(
            analysis_id="mock_undercut_placeholder",
            title="Mock Undercut Placeholder",
        ),
        MockAnalysisTask(
            analysis_id="mock_parting_placeholder",
            title="Mock Parting Placeholder",
        ),
    ]
