import {
  completePullDirection,
  type PullDirectionCompletionResult,
} from '../engineering-reports/pull-direction/pullDirectionCompletion';

import type {
  AnalysisIssueContract,
  AnalysisReportContract,
  AnalysisReportStatus,
  AnalysisSessionContract,
  AnalysisSessionState,
} from './analysisSession.contracts';

const DEFAULT_MOCK_ANALYSIS_IDS = [
  'mock_pull_direction_placeholder',
  'mock_draft_placeholder',
  'mock_undercut_placeholder',
  'mock_parting_placeholder',
] as const;

const MOCK_ANALYSIS_TITLES: Record<string, string> = {
  mock_pull_direction_placeholder: 'Pull Direction',
  mock_draft_placeholder: 'Mock Draft Placeholder',
  mock_undercut_placeholder: 'Mock Undercut Placeholder',
  mock_parting_placeholder: 'Mock Parting Placeholder',
};

export interface RunAnalysisSessionRequest {
  requestedAnalysisIds?: string[];
  warningAnalysisId?: string;
  fatalAnalysisId?: string;
}

export interface AnalysisSessionBridge {
  runMockAnalysisSession: (
    request?: RunAnalysisSessionRequest,
  ) => Promise<AnalysisSessionContract>;
}

function createSessionId(): string {
  return `mock-session-${Date.now().toString(36)}`;
}

function getAnalysisTitle(analysisId: string): string {
  return MOCK_ANALYSIS_TITLES[analysisId] ?? analysisId;
}

function createIssue(
  severity: AnalysisIssueContract['severity'],
  analysisId: string,
): AnalysisIssueContract {
  return {
    severity,
    code: severity === 'fatal' ? 'MOCK_FATAL' : 'MOCK_WARNING',
    message:
      severity === 'fatal'
        ? 'Mock fatal error generated by frontend bridge.'
        : 'Mock warning generated by frontend bridge.',
    analysisId,
  };
}

function createMockPullDirectionCompletion(): PullDirectionCompletionResult {
  return completePullDirection([
    {
      id: 'pull-positive-z',
      label: '+Z',
      direction: [0, 0, 1],
      rank: 1,
      score: 88,
    },
    {
      id: 'pull-positive-x',
      label: '+X',
      direction: [1, 0, 0],
      rank: 2,
      score: 71,
    },
    {
      id: 'pull-positive-y',
      label: '+Y',
      direction: [0, 1, 0],
      rank: 3,
      score: 52,
    },
  ]);
}

function createReport(params: {
  sessionId: string;
  analysisId: string;
  status: AnalysisReportStatus;
  issues?: AnalysisIssueContract[];
}): AnalysisReportContract {
  if (params.analysisId === 'mock_pull_direction_placeholder') {
    const completion = createMockPullDirectionCompletion();

    return {
      reportId: `${params.sessionId}:${params.analysisId}`,
      analysisId: params.analysisId,
      title: getAnalysisTitle(params.analysisId),
      status:
        completion.status === 'Poor'
          ? 'warning'
          : params.status,
      summary: completion.summary,
      issues: [
        ...(params.issues ?? []),
        ...completion.warnings.map((warning): AnalysisIssueContract => {
          return {
            severity: 'warning',
            code: 'PULL_DIRECTION_REVIEW',
            message: warning,
            analysisId: params.analysisId,
          };
        }),
      ],
      metadata: {
        mock: true,
        pullDirectionCompletion: completion,
      },
    };
  }

  return {
    reportId: `${params.sessionId}:${params.analysisId}`,
    analysisId: params.analysisId,
    title: getAnalysisTitle(params.analysisId),
    status: params.status,
    summary:
      params.status === 'failed'
        ? 'Mock analysis failed.'
        : params.status === 'warning'
          ? 'Mock analysis completed with warning.'
          : 'Mock analysis completed successfully.',
    issues: params.issues ?? [],
    metadata: {
      mock: true,
    },
  };
}

export function createMockAnalysisSessionContract(
  request: RunAnalysisSessionRequest = {},
): AnalysisSessionContract {
  const sessionId = createSessionId();
  const createdAt = new Date().toISOString();
  const startedAt = new Date().toISOString();

  const analysisIds =
    request.requestedAnalysisIds && request.requestedAnalysisIds.length > 0
      ? request.requestedAnalysisIds
      : [...DEFAULT_MOCK_ANALYSIS_IDS];

  const fatalIndex =
    request.fatalAnalysisId === undefined
      ? -1
      : analysisIds.indexOf(request.fatalAnalysisId);

  const executedAnalysisIds =
    fatalIndex >= 0 ? analysisIds.slice(0, fatalIndex + 1) : [...analysisIds];

  const reports = executedAnalysisIds.map((analysisId) => {
    if (analysisId === request.fatalAnalysisId) {
      return createReport({
        sessionId,
        analysisId,
        status: 'failed',
        issues: [createIssue('fatal', analysisId)],
      });
    }

    if (analysisId === request.warningAnalysisId) {
      return createReport({
        sessionId,
        analysisId,
        status: 'warning',
        issues: [createIssue('warning', analysisId)],
      });
    }

    return createReport({
      sessionId,
      analysisId,
      status: 'ok',
    });
  });

  const issues = reports.flatMap((report) => report.issues);

  let state: AnalysisSessionState = 'Completed';

  if (fatalIndex >= 0) {
    state = 'Failed';
  } else if (issues.some((issue) => issue.severity === 'warning')) {
    state = 'CompletedWithWarnings';
  }

  return {
    sessionId,
    state,
    createdAt,
    startedAt,
    endedAt: new Date().toISOString(),
    currentAnalysisId: null,
    queuedAnalysisIds: analysisIds,
    executedAnalysisIds,
    reportCount: reports.length,
    issueCount: issues.length,
    reports,
    issues,
  };
}

export function createMockAnalysisSessionBridge(): AnalysisSessionBridge {
  return {
    async runMockAnalysisSession(request?: RunAnalysisSessionRequest) {
      return createMockAnalysisSessionContract(request);
    },
  };
}
