import { createSplitFaceStoreCreator, selectActiveMoldBodies, selectSpruePresentationDefinitions, type SplitFaceStoreDeps, type SplitFaceState } from "./splitFace.store";
import { cancelDerivedMoldEvaluation, runDerivedMoldEvaluation as runDerivedMoldEvaluationProduction } from "../workflow";
import { designSprueProfile } from "../sprue-generation";
import type { ValidSpruePreviewPlacement } from "../sprue-generation/sprueGeneration.contracts";
import { createStore, type StoreApi } from "zustand/vanilla";
const runDerivedMoldEvaluation=vi.fn(runDerivedMoldEvaluationProduction);
const runCavityGenerationInWorker=Object.assign(vi.fn(async()=>{throw new Error("cavity worker not exercised by this suite");}),{cancel:vi.fn()}) as SplitFaceStoreDeps["runCavityGenerationInWorker"];
const cancelActiveCavityGeneration=vi.fn();
const k1={min:{x:0,y:0,z:0},max:{x:10,y:10,z:10}};
let useSplitFaceStore:StoreApi<SplitFaceState>;
const profileDesign=designSprueProfile(null);
const placement=(x=5):ValidSpruePreviewPlacement=>({status:"valid",topPoint:{x,y:5,z:30},cavityPoint:{x,y:5,z:20},inwardDirection:{x:0,y:0,z:-1},stemLengthMm:10,profileDesign,coordinateSpace:"mold-local"});
async function commitCutByFaceMold(face:"front"|"right"="front"){
 const s=useSplitFaceStore.getState();
 s.enterSelection();
 s.toggleFace(face);
 expect(await s.createMoldParts("m",k1)).toBe(true);
 const committed=useSplitFaceStore.getState();
 expect(committed.workflow).toBe("partsReady");
 expect(committed.lastCommittedResult).not.toBeNull();
 expect(selectActiveMoldBodies(committed)).not.toBeUndefined();
}
beforeEach(()=>{useSplitFaceStore=createStore(createSplitFaceStoreCreator({runDerivedMoldEvaluation,cancelDerivedMoldEvaluation,runCavityGenerationInWorker,cancelActiveCavityGeneration}));});
afterEach(()=>vi.restoreAllMocks());
describe("derived-state invalidation on Cut by Face topology edits",()=>{
 it("erasing the final cutting plane after a committed mold invalidates the committed result cluster atomically",async()=>{
  await commitCutByFaceMold();
  let s=useSplitFaceStore.getState();
  const hidden=s.definition!.moldBodies![0]!.id;
  s.setBodyVisibility(hidden,false);
  s=useSplitFaceStore.getState();
  expect(await s.createSprue(placement())).toBe(true);
  s=useSplitFaceStore.getState();
  expect(s.sprueDefinitions).toHaveLength(1);
  expect(selectSpruePresentationDefinitions(s)).toHaveLength(1);
  const revisionBefore=s.document.revision;
  expect(await s.removeSplitFaceAndRebuild("front","m",k1)).toBe(true);
  s=useSplitFaceStore.getState();
  expect(s.workflow).toBe("selectingFaces");
  expect(s.cuttingPlanes).toHaveLength(0);
  expect(s.definition).toBeNull();
  expect(s.lastCommittedResult).toBeNull();
  expect(selectActiveMoldBodies(s)).toBeUndefined();
  expect(s.sprues).toHaveLength(0);
  expect(s.sprueDefinitions).toHaveLength(0);
  expect(selectSpruePresentationDefinitions(s)).toHaveLength(0);
  expect(s.bodyVisibility).toEqual({});
  expect(s.cavity.status).toBe("unavailable");
  expect(s.cavity.result).toBeNull();
  expect(s.registration.status).toBe("unavailable");
  expect(s.document.revision).toBe(revisionBefore+1);
  expect(s.document.definition).toBeNull();
  expect(s.document.cuttingPlanes).toHaveLength(0);
  expect(s.evaluation.phase).toBe("idle");
  useSplitFaceStore.getState().undo();
  const restored=useSplitFaceStore.getState();
  expect(restored.lastCommittedResult).not.toBeNull();
  expect(restored.definition).not.toBeNull();
  expect(selectActiveMoldBodies(restored)).not.toBeUndefined();
 });
 it("a moved cutting plane on a committed mold invalidates the committed result cluster atomically",async()=>{
  await commitCutByFaceMold();
  let s=useSplitFaceStore.getState();
  const hidden=s.definition!.moldBodies![0]!.id;
  s.setBodyVisibility(hidden,false);
  s=useSplitFaceStore.getState();
  expect(await s.createSprue(placement())).toBe(true);
  s=useSplitFaceStore.getState();
  const revisionBefore=s.document.revision;
  const plane=s.cuttingPlanes[0]!.id;
  s.beginPlaneDrag(plane);
  s.commitPlaneDrag(plane,.5,k1);
  s=useSplitFaceStore.getState();
  expect(s.workflow).toBe("planesReady");
  expect(s.definition).toBeNull();
  expect(s.lastCommittedResult).toBeNull();
  expect(selectActiveMoldBodies(s)).toBeUndefined();
  expect(s.sprues).toHaveLength(0);
  expect(s.sprueDefinitions).toHaveLength(0);
  expect(selectSpruePresentationDefinitions(s)).toHaveLength(0);
  expect(s.bodyVisibility).toEqual({});
  expect(s.cavity.status).toBe("unavailable");
  expect(s.registration.status).toBe("unavailable");
  expect(s.document.revision).toBe(revisionBefore+1);
  expect(s.document.definition).toBeNull();
  expect(s.evaluation.phase).toBe("idle");
 });
 it("clearing the selection on a committed mold invalidates the committed result cluster atomically",async()=>{
  await commitCutByFaceMold();
  let s=useSplitFaceStore.getState();
  const revisionBefore=s.document.revision;
  s.clearSelection();
  s=useSplitFaceStore.getState();
  expect(s.workflow).toBe("selectingFaces");
  expect(s.definition).toBeNull();
  expect(s.lastCommittedResult).toBeNull();
  expect(selectActiveMoldBodies(s)).toBeUndefined();
  expect(s.sprues).toHaveLength(0);
  expect(s.sprueDefinitions).toHaveLength(0);
  expect(s.bodyVisibility).toEqual({});
  expect(s.cavity.status).toBe("unavailable");
  expect(s.registration.status).toBe("unavailable");
  expect(s.document.revision).toBe(revisionBefore+1);
  expect(s.document.definition).toBeNull();
  expect(s.evaluation.phase).toBe("idle");
 });
 it("selectActiveMoldBodies refuses a committed result that no longer matches the document once no replacement is in flight",async()=>{
  await commitCutByFaceMold();
  const committed=useSplitFaceStore.getState();
  expect(committed.evaluation.phase).toBe("complete");
  const served=selectActiveMoldBodies({definition:null,lastCommittedResult:committed.lastCommittedResult,bodyVisibility:{},document:committed.document,evaluation:committed.evaluation});
  expect(served).not.toBeUndefined();
  const mismatched=selectActiveMoldBodies({definition:null,lastCommittedResult:committed.lastCommittedResult,bodyVisibility:{},document:{...committed.document,revision:committed.document.revision+1},evaluation:committed.evaluation});
  expect(mismatched).toBeUndefined();
  const fingerprintMismatched=selectActiveMoldBodies({definition:null,lastCommittedResult:committed.lastCommittedResult,bodyVisibility:{},document:{...committed.document,fingerprint:"different"},evaluation:committed.evaluation});
  expect(fingerprintMismatched).toBeUndefined();
  const idle=selectActiveMoldBodies({definition:null,lastCommittedResult:committed.lastCommittedResult,bodyVisibility:{},document:{...committed.document,revision:committed.document.revision+1},evaluation:{...committed.evaluation,phase:"idle"}});
  expect(idle).toBeUndefined();
  const failed=selectActiveMoldBodies({definition:null,lastCommittedResult:committed.lastCommittedResult,bodyVisibility:{},document:{...committed.document,revision:committed.document.revision+1},evaluation:{...committed.evaluation,phase:"failed"}});
  expect(failed).toBeUndefined();
  const cancelled=selectActiveMoldBodies({definition:null,lastCommittedResult:committed.lastCommittedResult,bodyVisibility:{},document:{...committed.document,revision:committed.document.revision+1},evaluation:{...committed.evaluation,phase:"cancelled"}});
  expect(cancelled).toBeUndefined();
 });
 it("selectActiveMoldBodies serves the last committed result as bounded presentation continuity while a replacement for a newer document is genuinely evaluating",async()=>{
  await commitCutByFaceMold();
  const committed=useSplitFaceStore.getState();
  const inFlight=selectActiveMoldBodies({definition:null,lastCommittedResult:committed.lastCommittedResult,bodyVisibility:{},document:{...committed.document,revision:committed.document.revision+1},evaluation:{...committed.evaluation,phase:"evaluating"}});
  expect(inFlight).toEqual(selectActiveMoldBodies(committed));
 });
});
