import type { EngineeringReportDefinition } from './reportRegistry.types';

export const DEFAULT_ENGINEERING_REPORTS: readonly EngineeringReportDefinition[] = [
  {
    id: 'pull-direction',
    type: 'pull-direction',
    displayName: 'Pull Direction',
    description: 'Identifies the intended mold opening direction. Algorithm is not implemented in this stage.',
    category: 'moldability',
    displayOrder: 10,
    visible: true,
    supportStatus: 'coming-soon',
    version: '0.1.0',
    metadata: {
      chapter: '9',
      stage: '3',
    },
  },
  {
    id: 'draft-analysis',
    type: 'draft-analysis',
    displayName: 'Draft Analysis',
    description: 'Evaluates draft readiness. Algorithm is not implemented in this stage.',
    category: 'moldability',
    displayOrder: 20,
    visible: true,
    supportStatus: 'coming-soon',
    version: '0.1.0',
    metadata: {
      chapter: '9',
      stage: '3',
    },
  },
  {
    id: 'undercut-analysis',
    type: 'undercut-analysis',
    displayName: 'Undercut Analysis',
    description: 'Detects potential undercut regions. Algorithm is not implemented in this stage.',
    category: 'moldability',
    displayOrder: 30,
    visible: true,
    supportStatus: 'coming-soon',
    version: '0.1.0',
    metadata: {
      chapter: '9',
      stage: '3',
    },
  },
  {
    id: 'parting-analysis',
    type: 'parting-analysis',
    displayName: 'Parting Analysis',
    description: 'Prepares future parting line and parting surface analysis. Algorithm is not implemented in this stage.',
    category: 'manufacturing',
    displayOrder: 40,
    visible: true,
    supportStatus: 'coming-soon',
    version: '0.1.0',
    metadata: {
      chapter: '9',
      stage: '3',
    },
  },
  {
    id: 'thickness-analysis',
    type: 'thickness-analysis',
    displayName: 'Thickness Analysis',
    description: 'Prepares future wall thickness analysis. Algorithm is not implemented in this stage.',
    category: 'geometry',
    displayOrder: 50,
    visible: true,
    supportStatus: 'coming-soon',
    version: '0.1.0',
    metadata: {
      chapter: '9',
      stage: '3',
    },
  },
] as const;
